name: Sample Workflow
on:
  push: # enabling push event on main branch to fire the workflow
    branches:
      - main
  workflow_dispatch:
env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its subdirectory
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -alR
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files # this steps won't be showing any files as we didn't checkout our codes
        run: |
          pwd
          ls -alR

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Thank you
          VAR2: very much.
          VAR3: Enjoy !!!

  job4-AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::644107485976:role/github_actions_role #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity